const fs = require('node:fs');
const assert = require('node:assert/strict');
const proposal = fs.readFileSync('app/api/approvals/route.ts', 'utf8');
const execute = fs.readFileSync('app/api/approvals/[id]/execute/route.ts', 'utf8');
const admin = fs.readFileSync('lib/supabase/operator-admin.ts', 'utf8');
const migration = fs.readFileSync('supabase/migrations/202610040002_approved_mission_create.sql', 'utf8');
const page = fs.readFileSync('app/page.tsx', 'utf8');
assert.match(proposal, /sameOrigin\(request\)/);
assert.match(proposal, /workspace_write_access_required/);
assert.match(proposal, /status: 'pending'/);
assert.match(proposal, /approvalDigestForAudit/);
assert.match(execute, /approval\.requested_by !== user\.id/);
assert.match(execute, /approval\.status !== 'pending'/);
assert.match(execute, /approvalDigestForAudit\(action\) !== approval\.action_digest/);
assert.match(execute, /ultron_execute_mission_create/);
assert.match(admin, /import 'server-only'/);
assert.match(admin, /SUPABASE_SERVICE_ROLE_KEY/);
assert.match(migration, /for update/i);
assert.match(migration, /status = 'consumed'/);
assert.match(migration, /grant execute on function public\.ultron_execute_mission_create.*to service_role/i);
assert.match(migration, /verified_success/);
assert.match(page, /PREPARE APPROVAL PREVIEW/);
assert.match(page, /APPROVE & CREATE MISSION/);
assert.match(page, /Nothing has been created yet/);
assert.match(page, /Check Mission Control before retrying/);
console.log('Stage 7 approval-flow source checks: 18/18 passed');
